#!/usr/bin/env bash
# Regenerate THIRD_PARTY_LICENSES.generated.md from `cargo metadata`.
# Run from the repository root:
#
#   bash scripts/dump-licenses.sh
#
# The output file is git-ignored (regenerated as needed); the
# hand-curated THIRD_PARTY_LICENSES.md is the primary document.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
out="$repo_root/THIRD_PARTY_LICENSES.generated.md"

cargo metadata --format-version 1 > /tmp/cargo-metadata.json

python3 - "$out" <<'PY'
import json, sys
from collections import defaultdict
from pathlib import Path

out = Path(sys.argv[1])
metadata = json.loads(Path("/tmp/cargo-metadata.json").read_text())

deps = []
for pkg in metadata["packages"]:
    name = pkg["name"]
    if name.startswith("browsai"):
        continue
    deps.append((
        name,
        pkg["version"],
        pkg.get("license") or "NO_LICENSE",
        (pkg.get("repository") or "").strip(),
    ))
deps.sort()
by_licence = defaultdict(list)
for name, version, licence, repo in deps:
    by_licence[licence].append((name, version, repo))

lines = [
    "# BrowsAI Third-Party Licence Inventory (auto-generated)",
    "",
    "This file is regenerated by `bash scripts/dump-licenses.sh`. Do not",
    "edit it by hand; edit `THIRD_PARTY_LICENSES.md` instead and regenerate",
    "this file as part of the release process.",
    "",
    f"Total third-party packages: {len(deps)}",
    "",
]
for licence, pkgs in sorted(by_licence.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    lines.append(f"## {licence} ({len(pkgs)} packages)")
    lines.append("")
    for name, version, repo in pkgs:
        suffix = f" — {repo}" if repo else ""
        lines.append(f"- `{name}@{version}`{suffix}")
    lines.append("")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out}")
PY